### ISSUE TITLE
`python-package-init nixpkgs-pytools` is missing checkInputs = [ pytest ]

### ISSUE THREAD

**Issue by makefu** [nix-community/nixpkgs-pytools#10] opened 2019-05-09 08:07 UTC
when trying to package the `nixpkgs-pytools` with itself it seems to be missing `pytest` in `checkInputs`:
```nix
{ lib
, buildPythonPackage
, fetchPypi
, jinja2
, setuptools
}:

buildPythonPackage rec {
  pname = "nixpkgs-pytools";
  version = "1.0.1";

  src = fetchPypi {
    inherit pname version;
    sha256 = "0796c6e95daeb3d7e61c9c53126d95ba6a48f84b995b12b60f45619caf28a574";
  };

  propagatedBuildInputs = [
    jinja2
    setuptools
  ];

  meta = with lib; {
    description = "Tools for removing the tedious nature of creating nixpkgs derivations";
    homepage = https://github.com/nix-community/nixpkgs-pytools/;
    license = licenses.mit;
    # maintainers = [ maintainers. ];
  };
```

**Comment by costrouc** [comment] 2019-05-20 12:49
Looked into this and the issue is that pypi does not store all of the dependencies in the json api. So probably not worth using then? Take for example `https://pypi.org/pypi/nixpkgs-pytools/json`.

**Comment by makefu** [comment] 2019-05-20 13:55
@costrouc how come it does sometimes work? Where is the information coming from normally?

**Comment by costrouc** [comment] 2019-05-20 13:58
So the "neat" non trivial part of nixpkgs-pytools is that is mocks setuptools/distutils setup(...) method. With this approach it downloads the package, unzips, and runs setup.py. I should probably do this by default. Originally I thought that using the api could speed things up.

**Comment by makefu** [comment] 2019-05-21 08:07
i quite like the idea of mocking `setup.py` , i thought this is the default actually. Too bad the api does not respond with test requirements, probably because normally you do not need this info when installing the package.

**Comment by costrouc** [comment] 2019-07-26 16:47
This is now fixed in the latest master. Here is the generated code. Mocking setup(...) is now the default

```nix
{ lib
, buildPythonPackage
, fetchPypi
, pytest
, jinja2
, setuptools
}:

buildPythonPackage rec {
  pname = "nixpkgs-pytools";
  version = "1.0.1";

  src = fetchPypi {
    inherit pname version;
    sha256 = "0796c6e95daeb3d7e61c9c53126d95ba6a48f84b995b12b60f45619caf28a574";
  };

  checkInputs = [
    pytest
  ];

  propagatedBuildInputs = [
    jinja2
    setuptools
  ];

  meta = with lib; {
    description = "Tools for removing the tedious nature of creating nixpkgs derivations";
    homepage = https://github.com/nix-community/nixpkgs-pytools/;
    license = licenses.mit;
    # maintainers = [ maintainers. ];
  };
}
```

**Closed as completed by costrouc** 2019-07-26 16:47 UTC
